const eventsData = [
  {
    id: 1,
    slug: "2026-diocesan-prayer-convocation",
    date: "APRIL 19, 2026",
    title: "2026 Diocesan Prayer Convocation: Enriched By Him In Everything",
    image: "https://drop-bibbi4ujk-onyekachidegreats-projects.vercel.app/uzqgclibqdvtgusovg1b",
    category: "Convocation",
    content: [
      "From Thursday, April 16th to Sunday, April 19th, 2026, the Anglican Diocese of Calabar gathered at Holy Trinity College, Asari Eso Layout, for a spiritually transformative Diocesan Prayer Convocation. Anchored on the Pauline envisioned theme, 'Enriched by Him in Everything' (1 Cor 1:5), the four-day convocation was a period of deep spiritual renewal, intense prayer, fasting, and profound scriptural learning.",
      "THE PROGRAMME OF ACTIVITIES",
      "The convocation kicked off on Thursday evening with arrivals, registration, and a powerful Opening Charge and Variety session led by Rev. Alexandar Nweke. By Friday morning, the spiritual atmosphere was fully set with a Holy Communion Service, followed by the first Bible Study session led by Ven. Prof. Ephraim Osai. Throughout the event, delegates were blessed with rigorous daily schedules that included 'Prayer! Prayer!!' sessions by Rev. Riman Urom, Faith Clinics with Ven. John Uka, Health Talks by Dr. Chigozie Uzomba, and 'Time with the Bishop'.",
      "EXPOSITION ON THE THEME",
      "At the heart of the convocation were the powerful Expositions delivered by the Diocesan Bishop, the Rt. Rev. Prof. Nneoyi Onen Egbe. A major focus of the study was being 'Grounded in Grace, Mercy, and Favour'. Delegates were taught that believers are saved by God's grace, not by human effort. The teachings emphasized that divine providence involves God's active guidance and sustenance, requiring believers to be spiritually regenerated, trust Him fully, and avoid diverse temptations.",
      "SEMINAR: GROWING IN FAITH (By Ven. S. O. Ukachukwu)",
      "A major highlight of the convocation was the seminar on 'Growing in Faith'. Ven. Ukachukwu taught that faith is strictly organic it is a living entity, not a mechanical process. Likened to a mustard seed (Luke 17:6), faith must take root in Christ to draw life, grow abundantly, and bear visible fruit. He outlined the growth cycle of faith, from the 'Birth stage' (being born again through the Word), to 'Infancy' (adjusting to elementary doctrines), 'Adolescence', and finally 'Maturity' (the measure of the stature of Christ).",
      "The facilitator also corrected wrong impressions about faith, noting that faith does not grow automatically without effort, nor is it merely a product of subjective emotions or motivational speaking. He warned delegates that faith can be violently attacked through emotional infiltrations such as fear, unresolved anger, pride, anxiety, unforgiveness, and discouragement. A stern warning was given: 'Don't compare your faith with others.' Because God gives different measures of faith, comparing oneself leads only to pride or despair.",
      "To truly grow, believers were encouraged to embrace community life. 'Your faith gets stronger rubbing against other believers. Iron sharpens iron,' he noted, emphasizing that a horizontally grown faith (love for brethren) proves a vertically grown faith (love for God).",
      "WORKSHOP: HINDRANCES TO GOD'S ABUNDANT SUPPLY (By Rev. Canon Stanley Timothy Iwuji)",
      "Another highly anticipated session was the workshop on divine provision. Rev. Canon Iwuji established a fundamental truth: 'God is not limited in supply He is unlimited. The real issue is not God's ability to give, but man's capacity to receive.'",
      "He outlined major hindrances that restrict the flow of God's blessings, favor, and purpose in a person's life. The first is 'Sin and Disobedience', which acts as a barrier that disconnects a man from divine flow (Isaiah 59:1-2). The second major hindrance discussed was 'Unbelief and Lack of Faith', as doubt directly cancels access to divine provision (Hebrews 11:6). Delegates were challenged to clear these spiritual, mental, and behavioral blocks to access God's financial provision, wisdom, peace, and health.",
      "WORKSHOP: THE POWER TO MAKE WEALTH (By Ven. Joseph Ighomereho)",
      "Complementing the teachings on abundance, Ven. Joseph Ighomereho led a practical and spiritually grounded workshop on the power to make wealth, ensuring delegates understood the balance between spiritual devotion and godly prosperity.",
      "CONCLUSION",
      "The convocation culminated on Saturday evening with an explosive 'Praise Unlimited' session, followed by a glorious Thanksgiving Service on Sunday morning. Delegates departed Holy Trinity College not just spiritually recharged, but deeply enriched in knowledge, armed with practical tools to defend their faith, access divine abundance, and remain a blessing to this generation.",
    ],
  },
  {
    id: 2,
    slug: "foundation-laying-women-retreat-centre",
    date: "APRIL 20, 2026",
    title:
      "Upcoming: Foundation Laying Service for the Diocesan Women Retreat Centre",
    image: "https://drop-bibbi4ujk-onyekachidegreats-projects.vercel.app/qtfltwjrr3pdr3fvcfqv",
    category: "Upcoming Event",
    content: [
      "The Anglican Diocese of Calabar cordially invites all clergy, lay delegates, parishioners, and well-wishers to a highly anticipated and historic occasion: the Foundation Laying Service of the brand new Diocesan Women Retreat Centre.",
      "This landmark event is scheduled to take place on Saturday, 25th April, 2026, starting promptly at 2:00 PM. The service will be held at the project site, located at Bacoco Village (just after Nassarawa).",
      "A VISION FOR SPIRITUAL RENEWAL",
      "The Diocesan Women Retreat Centre is a visionary project spearheaded by the Diocesan Women's Ministry (Mothers' Union and Women's Guild). Once completed, this center will serve as a dedicated sanctuary for spiritual renewal, prayer fasting, empowerment programs, and fellowship for women across the Diocese and beyond. It stands as a testament to the unwavering faith and dedication of our mothers in building the church.",
      "OFFICIATED BY THE BISHOP",
      "The foundation laying ceremony will be officially performed by our Diocesan Bishop, The Rt. Rev'd. Prof. Nneoyi Onen Egbe. Under his dynamic spiritual leadership, the Diocese continues to expand its physical and spiritual footprint, ensuring that well-equipped spaces are available to nurture the faith of every group within the Anglican communion.",
      "CALL FOR SUPPORT AND ATTENDANCE",
      "We are calling on all members of the Diocesan family to come out in their numbers to witness, celebrate, and support this great work. Let us gather together at Bacoco to commit this building project into the hands of the Almighty God, praying for divine provision, safety for the workers, and a speedy, successful completion.",
      "Mark your calendars, spread the word, and make plans to be there!",
    ],
  },
  {
    id: 3,
    slug: "ascension-elevated-to-archdeaconry",
    date: "MAY 15, 2026",
    title:
      "Historic Milestone: Ascension Deanery Elevated to a Full-Fledged Archdeaconry",
    image:
      "https://i.postimg.cc/5ttghzDk/697792999-122156910344973012-3823485635920366546-n.jpg",
    category: "News",
    content: [
      "On Ascension Day, Thursday, May 14th, 2026, the Anglican Diocese of Calabar witnessed a historic spiritual milestone as the Anglican Church of Ascension, located at 8 Miles, Ikot Omin, Calabar, was officially elevated from a Deanery to a full-fledged Archdeaconry.",
      "The glorious and heavily attended service was officiated by the Diocesan Bishop, The Rt. Rev'd. Prof. Nneoyi Onen Egbe. During the service, the Bishop also presided over the official re-dedication of the church building and the dedication of the vicarage.",
      "This elevation is a profound testament to the resilient faith of the Ascension congregation and the collective labor of many devoted leaders over 36 years. Birthed in 1990 by Rev. W. G. Ekprikpo (who later became the Pioneer Bishop of Calabar Diocese), the church started as a mustard seed with about four families under the leadership of its first vicar, Rev. Thompson Chijioke Onuoha.",
      "The early congregation faced numerous foundational challenges, from losing their initial land to being banned from using a government school, and even worshipping under a mango tree. Through these trying times, the baton of leadership was passed to dedicated priests, including Rev. Prince Christian Anyim in 2003.",
      "Shortly after, a major turning point occurred under the leadership of Ven. Bar. Dr. Lawrence Ngozi Umar. He and his ministerial team tirelessly navigated struggles to acquire the church's permanent site in July 2004, completing the first church hall in 2008 and dedicating the first worship building in 2011.",
      "Building upon this incredibly solid foundation, Ven. Prof. Chibueze Haggai Njoku, who became Vicar in 2016, worked with unwavering dedication alongside past and present assisting priests and mission workers including Rev. Charles Esien Eyo, Rev. Canon Chijioke Osigwe, Rev. Isaac Nwafor, Rev. Canon Sunday Joel Emerionwu, and currently Ven. Ogbuji Justin they guided the church through massive spiritual and structural expansion.",
      "The Diocese rejoices with the newly inaugurated Ascension Archdeaconry. We celebrate the pioneer families, the past leaders who planted and watered, and the present leadership experiencing the harvest. We pray that this new status will spur even greater exploits for the Kingdom of God. To God be the glory!",
    ],
  },
  {
    id: 4,
    slug: "synod-registration-verify-receipt",
    date: "MAY 20, 2026",
    title:
      "IMPORTANT UPDATE: How to Complete Your Synod Registration if You Already Paid",
    image: "https://i.postimg.cc/Mp0byVLS/Screenshot-2026-06-04-112956.png",
    category: "Update",
    content: [
      "Calvary greetings to you all.",
      "We have noticed that some delegates successfully paid their registration fee, but their network dropped or their browser tab closed before they could complete the final step to generate their Unique Delegate ID.",
      'To resolve this, we have added a "Verify Receipt" feature. If you have already been debited and received a Paystack receipt in your email, please DO NOT pay again. Follow these simple steps to claim your payment and complete your registration:',
      '<strong>Step 1: Return to the Registration Form</strong><br>Go back to the registration page. Good news: If you are using the same phone or computer as before, the system has automatically saved your progress! Your Personal Details will likely be pre-filled for you. If you are using a different device, don\'t worry—simply fill in your details again normally. Just review your info, re-upload your photo if prompted, and click next until you reach the Payment Step.<br><br><img src="https://i.postimg.cc/52m8RvMJ/Whats-App-Image-2026-06-04-at-12-33-29.jpg" alt="Payment step of the form" style="width:100%; border-radius:8px; margin-top:10px;" />',
      '<strong>Step 2: Click \'Verify Receipt\'</strong><br>Instead of clicking "Proceed to Payment", scroll down to the bottom of that section and click the link that says: <strong>"Already paid but tab closed? Verify Receipt"</strong>.<br><br><img src="https://i.postimg.cc/C1nBSn96/Whats-App-Image-2026-06-04-at-12-34-29.jpg" alt="Highlighting the text link button at the bottom" style="width:100%; border-radius:8px; margin-top:10px;" />',
      '<strong>Step 3: Enter your Paystack Reference</strong><br>A pop-up box will appear asking for your Reference ID. Go to the email address you used to pay, open your Paystack email receipt, copy the Reference ID, paste it into the box, and click <strong>"Verify Receipt"</strong>.<br><br><img src="https://i.postimg.cc/zBY5HLVw/Whats-App-Image-2026-06-04-at-12-40-26.jpg" alt="Verify Payment pop-up box and input field" style="width:100%; border-radius:8px; margin-top:10px;" />',
      '<strong>Step 4: Confirm Your Details</strong><br>The system will instantly find your payment and display your <strong>Email, Payment Channel, and the Amount paid.</strong> If the details are correct, click <strong>"Proceed".</strong><br><br><img src="https://i.postimg.cc/MGCZ0PrK/Whats-App-Image-2026-06-04-at-12-36-42.jpg" alt="Transaction Found confirmation box" style="width:100%; border-radius:8px; margin-top:10px;" />',
      '<strong>Step 5: Complete Your Registration</strong><br>The pop-up will close, and the main payment button will now change to <strong>"Complete Registration" button.</strong> Click it to finalize your submission and instantly generate your Delegate ID!<br><br><img src="https://i.postimg.cc/htJqC8m7/Whats-App-Image-2026-06-04-at-12-37-13-(1).jpg" alt="Green Complete Registration button" style="width:100%; border-radius:8px; margin-top:10px;" />',
      "If you experience any issues verifying your receipt, please reach out to the admin or technical team with a screenshot of your Paystack email receipt.",
      "Thank you, and God bless!",
    ],
  },
  {
    id: 5,
    slug: "2026-democracy-day-thanksgiving-service",
    date: "JUNE 13, 2026",
    title:
      "Cross River State Government Holds 2026 Democracy Day Thanksgiving at Holy Trinity Cathedral",
    image: "https://i.postimg.cc/fyys7KBT/1000885649-1.jpg",
    category: "News",
    content: [
      "The Cathedral Church of the Holy Trinity, Calabar, was filled with praise and gratitude on Friday as it played host to the Cross River State Government for the 2026 Democracy Day Interdenominational Thanksgiving Service.",
      "The highly attended service brought together top government officials, political leaders, clergy, and worshippers. Representing the State Governor, Senator Prince Bassey Edet Otu, the Deputy Governor, Rt. Hon. Peter Odey, led the state's delegation to thank God for the nation's democratic journey.",
      "THE CHURCH'S ROLE AND A CALL FOR ACCOUNTABILITY",
      "Delivering a powerful sermon, the Bishop of the Anglican Diocese of Calabar, The Rt. Rev'd. Prof. Nneoyi Onen Egbe, preached from 2 Chronicles 31:1–7, James 4:13–5:6, and Hebrews 12:28. He emphasized the importance of gratitude as a catalyst for divine favor. The Bishop commended the administration of Governor Otu for the numerous completed, ongoing, and newly awarded projects across the state, noting that the Governor’s success reflects positively on Christian ministry in Nigeria.",
      "Touching on national issues, the cleric urged public officials to mirror transparency by publishing annual performance reports. He also announced the commencement of a three-day national mourning period declared by the Christian Association of Nigeria (CAN) in response to the insecurity in parts of the country, calling on the congregation to stand in the gap for the nation.",
      "Delivering the Governor's message, Deputy Gov. Hon. Odey reflected on the profound significance of June 12 in Nigeria’s history, describing the 1993 presidential election as a watershed moment. He recalled the uncommon courage of patriotic Nigerians who stood against military rule, noting that while their voices were temporarily gagged, their resolve laid the foundation for the 1999 restoration of democracy, which has now endured uninterrupted for 27 years.",
      "He reminded the congregation that power ultimately belongs to the people, stressing that the Otu administration’s governing philosophy, 'People First,' is deeply rooted in these democratic ideals. 'When we construct and maintain roads, we are not merely providing infrastructure for aesthetics; we are creating opportunities for our people to pursue their daily economic activities without hindrance,' Odey stated.",
      "The Deputy Governor further highlighted the state's massive agricultural drive cultivating cocoa, oil palm, coffee, cassava, and rice as a push for both food security and boundless agribusiness opportunities. Referencing the recent presentation of the administration’s three-year scorecard, he pointed to investments in electricity, healthcare, and enterprise development as proof of their commitment to transparency, accountability, and the 'Think Cross River' initiative.",
      "The service concluded with fervent prayers for the state and the nation, answering the Deputy Governor's appeal for the Church to continually seek divine wisdom and guidance for the leadership.",
      "<hr style='margin: 30px 0; border: 0; border-top: 1px solid #eee;' />",
      "<h3 style='text-align: center; margin-bottom: 20px;'>Event Gallery</h3>",
      "<!-- Replace the src links below with your actual image links from postimg -->",
      "<img src='https://i.postimg.cc/nz0ZQ5Ky/1000885651-1.jpg' alt='Democracy Day Thanksgiving 1' style='width:100%; border-radius:8px; margin-bottom:20px;' />",
      "<img src='https://i.postimg.cc/1tJPNTcN/1000885648-1.jpg' alt='Democracy Day Thanksgiving 2' style='width:100%; border-radius:8px; margin-bottom:20px;' />",
    ],
  },
  {
    id: 6,
    slug: "nawada-8-week-parenting-series",
    date: "JUNE 16, 2026",
    title:
      "NAWADA Diocese of Calabar: 8-Week Substance Abuse Prevention Series for Parents",
    image: "https://i.postimg.cc/cCMjNVVh/IMG-20260616-WA0021.jpg",
    category: "NAWADA",
    content: [
      "The Nigerian Anglican War Against Drug Abuse (NAWADA), Diocese of Calabar, has officially released a comprehensive 8-week parenting guide focused on substance abuse prevention.",
      "Spanning from the Epiphany season through Lent, the series equips parents with practical wisdom and prayers to build resilient, faith-filled homes.",
      "A CALL TO INTENTIONAL PARENTING",
      "The weekly focus areas are designed to tackle the root causes of vulnerability in children:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Week 1:</strong> Emphasizes that prevention starts at home, noting that loved and supported children are less likely to abuse drugs.</li>",
      "<li style='margin-bottom: 10px;'><strong>Week 2:</strong> Highlights that strong parent-child bonding acts as powerful protection, urging parents to make time to listen.</li>",
      "<li style='margin-bottom: 10px;'><strong>Week 3:</strong> Reminds parents that children learn by observing actions rather than just words, encouraging them to be the example.</li>",
      "<li style='margin-bottom: 10px;'><strong>Week 4:</strong> Focuses on setting clear family rules to guide children and reduce risky behavior.</li>",
      "<li style='margin-bottom: 10px;'><strong>Week 5:</strong> Advocates for open and honest communication to prevent secrecy and curiosity.</li>",
      "<li style='margin-bottom: 10px;'><strong>Week 6:</strong> Entering the Lenten season of discipline, it teaches children how to confidently say 'NO' to peer pressure.</li>",
      "<li style='margin-bottom: 10px;'><strong>Week 7:</strong> Encourages praising good behavior to build confidence and resilience.</li>",
      "<li style='margin-bottom: 10px;'><strong>Week 8:</strong> Advises parents to know their child's friends and daily activities, emphasizing that 'supervision is love'.</li>",
      "</ul>",
      "Each week features a dedicated prayer, asking the Heavenly Father to grant parents wisdom, protect children from harmful influences, and make homes a place of peace, faith, and godly values.",
      "<hr style='margin: 30px 0; border: 0; border-top: 1px solid #eee;' />",
      "<h3 style='text-align: center; margin-bottom: 20px;'>Weekly Guide Gallery</h3>",
      "<!-- Replace the src links below with your actual image links for all 8 weeks -->",
      "<img src='https://i.postimg.cc/cCMjNVVh/IMG-20260616-WA0021.jpg' alt='NAWADA Week 1' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
      "<img src='https://i.postimg.cc/kMxL8bBr/IMG-20260616-WA0023.jpg' alt='NAWADA Week 2' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
      "<img src='https://i.postimg.cc/Zq2XPP89/IMG-20260616-WA0022.jpg' alt='NAWADA Week 3' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
      "<img src='https://i.postimg.cc/15s2K3qz/IMG-20260616-WA0024.jpg' alt='NAWADA Week 4' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
      "<img src='https://i.postimg.cc/mZQKMHhq/IMG-20260616-WA0027.jpg' alt='NAWADA Week 5' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
      "<img src='https://i.postimg.cc/wxhnJm3n/IMG-20260616-WA0025.jpg' alt='NAWADA Week 6' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
      "<img src='https://i.postimg.cc/kMxL8bBb/IMG-20260616-WA0026.jpg' alt='NAWADA Week 7' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
      "<img src='https://i.postimg.cc/MZygRQvV/IMG-20260616-WA0028.jpg' alt='NAWADA Week 8' style='width:100%; max-width:500px; display:block; margin: 0 auto 20px; border-radius:8px; box-shadow: 0 4px 10px rgba(0,0,0,0.1);' />",
    ],
  },
  {
    id: 7,
    slug: "nawada-week-23-goals-and-purpose",
    date: "JUNE 23, 2026",
    title: "NAWADA Week 23: Children with Goals and Purpose Avoid Destructive Habits",
    image: "https://i.postimg.cc/76TDmyjF/IMG-20260629-WA0001.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 23 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign by the Diocese of Calabar.",
      "This week, our focus is on empowering our children. The core message is clear: <strong>Children with goals and purpose avoid destructive habits.</strong>",
      "As parents and guardians, we must guide our children to:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Set Goals:</strong> Help them identify what they want to achieve in the short and long term.</li>",
      "<li style='margin-bottom: 10px;'><strong>Stay Focused:</strong> Encourage them to keep their eyes on their goals despite distractions.</li>",
      "<li style='margin-bottom: 10px;'><strong>Build Dreams:</strong> Nurture their ambitions and support their passions.</li>",
      "<li style='margin-bottom: 10px;'><strong>Live with Purpose:</strong> Instill in them a sense of meaning and direction in life.</li>",
      "</ul>",
      "A purposeful child has a brighter future and is far less likely to fall into the trap of drugs and alcohol. Let us say NO to drugs and alcohol.",
      "<strong>Theme: Empowerment</strong>",
      "<em>Holy Spirit, Fill our families with Your power. Give our children boldness to say no to drugs and alcohol. Empower us as parents to speak truth with wisdom and compassion. Let Your Spirit guide every decision in our homes. Amen.</em>"
    ],
  },
  {
    id: 8,
    slug: "nawada-week-24-monitoring-is-guidance",
    date: "JUNE 30, 2026",
    title: "NAWADA Week 24: Monitoring is Guidance, Not Lack of Trust",
    image: "https://i.postimg.cc/J0V8F2WS/IMG-20260629-WA0000.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 24 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign by the Diocese of Calabar.",
      "This week, we emphasize the importance of parental oversight. Remember: <strong>Monitoring is guidance, not lack of trust.</strong>",
      "To provide strong guidance and ensure safe children, parents should:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Know Who They Are With:</strong> Be aware of your children's friends and acquaintances.</li>",
      "<li style='margin-bottom: 10px;'><strong>Know Where They Are Going:</strong> Always know your children's whereabouts.</li>",
      "<li style='margin-bottom: 10px;'><strong>Talk Openly & Often:</strong> Maintain open lines of communication so they feel comfortable sharing with you.</li>",
      "<li style='margin-bottom: 10px;'><strong>Guide with Love, Not Fear:</strong> Let your guidance be rooted in love and concern for their well-being, rather than intimidation.</li>",
      "</ul>",
      "Strong guidance leads to safe children and bright futures. Let us confidently say NO to drugs and alcohol.",
      "<strong>Theme: Empowerment</strong>",
      "<em>Holy Spirit, Fill our families with Your power. Give our children boldness to say no to drugs and alcohol. Empower us as parents to speak truth with wisdom and compassion. Let Your Spirit guide every decision in our homes. Amen.</em>"
    ],
  },
  {
    id: 9,
    slug: "nawada-week-25-teach-decision-making",
    date: "JULY 7, 2026",
    title: "NAWADA Week 25: Teach Decision-Making - Think, Pray, Choose Wisely",
    image: "https://i.postimg.cc/7h84RWk8/IMG-20260706-WA0002.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 25 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign.",
      "As we enter the July Trinity Season focusing on Godly Foundations, this week's message is: <strong>Teach decision-making: think, pray, choose wisely.</strong>",
      "Equipping our children with good decision-making skills is vital for their protection:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Think:</strong> Teach them to evaluate the consequences of their actions before taking them.</li>",
      "<li style='margin-bottom: 10px;'><strong>Pray:</strong> Encourage them to seek God's guidance in every situation.</li>",
      "<li style='margin-bottom: 10px;'><strong>Choose Wisely:</strong> Help them make choices that align with godly values and their long-term well-being.</li>",
      "</ul>",
      "Let us build strong families and bright futures by saying NO to drugs and alcohol.",
      "<strong>Theme: Stability & Order</strong>",
      "<em>Triune God, Establish strong foundations in our families. Let love, accountability, and clear rules guard our children from risky behavior. May our homes reflect unity, order, and spiritual stability. Amen.</em>"
    ],
  },
  {
    id: 10,
    slug: "nawada-week-26-address-behavior-issues",
    date: "JULY 14, 2026",
    title: "NAWADA Week 26: Address Behavior Issues Early Before They Grow",
    image: "https://i.postimg.cc/Y0K7PsH7/IMG-20260720-WA0014.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 26 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign.",
      "Continuing our July Trinity Season focus on Godly Foundations, we look at the importance of early intervention: <strong>Address behavior issues early before they grow.</strong>",
      "Small issues can escalate if left unattended. Parents must:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Notice Early:</strong> Pay close attention to changes in your child's behavior, mood, or habits.</li>",
      "<li style='margin-bottom: 10px;'><strong>Talk Openly:</strong> Address concerning behaviors immediately through honest, loving conversations.</li>",
      "<li style='margin-bottom: 10px;'><strong>Guide Consistently:</strong> Apply rules and discipline consistently to reinforce positive behavior.</li>",
      "</ul>",
      "Early action builds strong families and bright futures. Stand firm and say NO to drugs and alcohol.",
      "<strong>Theme: Stability & Order</strong>",
      "<em>Triune God, Establish strong foundations in our families. Let love, accountability, and clear rules guard our children from risky behavior. May our homes reflect unity, order, and spiritual stability. Amen.</em>"
    ],
  },
  {
    id: 11,
    slug: "nawada-week-27-healthy-hobbies-sports",
    date: "JULY 20, 2026",
    title: "NAWADA Week 27: Encourage Healthy Hobbies and Sports",
    image: "https://i.postimg.cc/0QJxcqh6/IMG-20260720-WA0013.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 27 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign by the Diocese of Calabar.",
      "As we focus on Godly Foundations during this Trinity Season, our message for this week is: <strong>Encourage healthy hobbies and sports.</strong>",
      "Keeping our youth positively engaged is a powerful deterrent against substance abuse. We encourage parents to help their children:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Stay Active:</strong> Physical activity promotes physical and mental well-being.</li>",
      "<li style='margin-bottom: 10px;'><strong>Discover Talents:</strong> Support them in exploring new skills, arts, and interests.</li>",
      "<li style='margin-bottom: 10px;'><strong>Build Confidence:</strong> Mastering a hobby or sport significantly boosts self-esteem.</li>",
      "<li style='margin-bottom: 10px;'><strong>Make Positive Choices:</strong> Time spent on productive activities leaves no room for destructive habits.</li>",
      "</ul>",
      "Healthy habits create strong families and bright futures. Let us continue to say NO to drugs and alcohol.",
      "<strong>Theme: Stability & Order</strong>",
      "<em>Triune God, Establish strong foundations in our families. Let love, accountability, and clear rules guard our children from risky behavior. May our homes reflect unity, order, and spiritual stability. Amen.</em>"
    ],
  },
  {
    id: 12,
    slug: "nawada-week-28-peaceful-homes",
    date: "JULY 27, 2026",
    title: "NAWADA Week 28: Peaceful Homes Raise Emotionally Healthy Children",
    image: "https://i.postimg.cc/LX556BsR/IMG-20260727-WA0031.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 28 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign by the Diocese of Calabar.",
      "As we continue our focus on Godly Foundations during this Trinity Season, our message for this week is: <strong>Peaceful homes raise emotionally healthy children.</strong>",
      "A peaceful home environment is crucial for a child's emotional development. Parents can foster this by:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Peace at Home:</strong> Create an atmosphere of calm and safety where children feel secure.</li>",
      "<li style='margin-bottom: 10px;'><strong>Strong Families:</strong> Build strong bonds through love, understanding, and mutual respect.</li>",
      "<li style='margin-bottom: 10px;'><strong>Emotional Health:</strong> Nurture their emotional well-being by listening and validating their feelings.</li>",
      "<li style='margin-bottom: 10px;'><strong>Safe Futures:</strong> Provide a stable foundation that guides them away from destructive choices.</li>",
      "</ul>",
      "Peaceful homes. Strong children. Bright tomorrows. Let us stand together and say NO to drugs and alcohol.",
      "<strong>Theme: Stability & Order</strong>",
      "<em>Triune God, Establish strong foundations in our families. Let love, accountability, and clear rules guard our children from risky behavior. May our homes reflect unity, order, and spiritual stability. Amen.</em>"
    ],
  },
  {
    id: 13,
    slug: "nawada-week-29-correct-in-love",
    date: "AUGUST 3, 2026",
    title: "NAWADA Week 29: Correct in Love; Avoid Harsh Punishment",
    image: "https://i.postimg.cc/W4PYBk63/IMG-20260803-WA0032.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 29 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign by the Diocese of Calabar.",
      "As we enter the August Trinity Season focusing on Stewardship of Children, our message for this week is: <strong>Correct in love; avoid harsh punishment.</strong>",
      "Disciplining children with love and understanding helps build a secure environment. Parents can achieve this by:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Love & Guide:</strong> Correct behavior by guiding them towards the right path with compassion.</li>",
      "<li style='margin-bottom: 10px;'><strong>Listen Actively:</strong> Pay attention to their thoughts and feelings before reacting.</li>",
      "<li style='margin-bottom: 10px;'><strong>Communicate Openly:</strong> Maintain an open dialogue to understand the root of their actions.</li>",
      "<li style='margin-bottom: 10px;'><strong>Protect Them:</strong> Shield them from harmful influences through loving boundaries.</li>",
      "</ul>",
      "Faithful parents. Responsible children. Bright futures. Let us stand together and say NO to drugs and alcohol.",
      "<strong>Theme: Responsibility</strong>",
      "<em>Lord, Help us to be faithful stewards of the children You have given us. Teach us to listen, communicate openly, and guide them wisely. Protect them from friends and environments that promote substance abuse. Amen.</em>"
    ],
  },
  {
    id: 14,
    slug: "nawada-week-31-discuss-mistakes",
    date: "AUGUST 17, 2026",
    title: "NAWADA Week 31: Let Children Know Mistakes Can Be Discussed, Not Hidden",
    image: "https://i.postimg.cc/SKp1BM7b/IMG-20260817-WA0011.jpg",
    category: "NAWADA",
    content: [
      "Welcome to Week 31 of the Nigerian Anglican War Against Drug Abuse (NAWADA) campaign by the Diocese of Calabar.",
      "Continuing our focus on Stewardship of Children this August Trinity Season, our message for this week is: <strong>Let children know mistakes can be discussed, not hidden.</strong>",
      "Fostering an environment where children feel safe to admit their faults is vital. Parents can encourage this by:",
      "<ul>",
      "<li style='margin-bottom: 10px;'><strong>Open Conversation:</strong> Create a safe space for them to speak without fear of immediate judgment.</li>",
      "<li style='margin-bottom: 10px;'><strong>Build Trust:</strong> Ensure they know your love is unconditional, even when they fail.</li>",
      "<li style='margin-bottom: 10px;'><strong>Listen Actively:</strong> Hear their side of the story and understand their perspective.</li>",
      "<li style='margin-bottom: 10px;'><strong>Guide Wisely:</strong> Help them learn from their mistakes rather than just penalizing them.</li>",
      "<li style='margin-bottom: 10px;'><strong>Protect Their Future:</strong> Proper guidance turns mistakes into stepping stones for a brighter future.</li>",
      "</ul>",
      "Strong parents. Strong children. Bright futures. Let us stand together and say NO to drugs and alcohol.",
      "<strong>Theme: Responsibility</strong>",
      "<em>Lord, Help us to be faithful stewards of the children You have given us. Teach us to listen, communicate openly, and guide them wisely. Protect them from friends and environments that promote substance abuse. Amen.</em>"
    ],
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = eventsData;
}
